### ISSUE TITLE
[question] Purpose of setReplicas

### ISSUE THREAD

**Issue by heidemn** [galexrt/kubernetes-keycloak#6]
Thanks for creating this project.

I'm trying to understand how the setup works:

Can you explain a bit what the purpose of the `setReplicas` function in `configmap.yaml/run.sh` is?
I understand that this is to make each Keycloak Pod aware of all other Pods.
Is this only required to ensure the correct operation of the distributed Infinispan cache? Or are there other reasons why this is needed?

Also, I saw in your docs that `AUTO_INJECT_HOSTS` is "not used right now".
Does this mean that the number of Pods must remain constant while the StatefulSet is running?
Which steps would be required to change the number of Pods later?

**Comment by galexrt** [comment]
> Can you explain a bit what the purpose of the setReplicas function in configmap.yaml/run.sh is?

This repo currently is simply adding the Pods to the list of infinispan nodes. There are better ways, e.g, the helm chart which uses DNS discovery for the infinispan node discovery.
Setting the "nodes" is needed for the infinispan cache.

> Does this mean that the number of Pods must remain constant while the StatefulSet is running?

No, you can change it.

> Which steps would be required to change the number of Pods later?

Just scale it as needed, though you may want to scale down one by one so the infinispan cache doesn't "break" for whatever reason. In general you shouldn't go below the set `KEYCLOAK_OWNERS_COUNT` as otherwise the cache doesn't have enough "owners" and should go bad then.

**Comment by galexrt** [comment]
Closing as questions have been answered and there has been no response for some time.

**Comment by heidemn** [comment]
Thanks a lot for the explanation.
